from construct import *


skills_list =(
    'attack', 'kick', 'throw', 'unsummon', 'left_hand_throw',
    'left_hand_swing', 'magic_arrow', 'fire_arrow', 'inner_sight',
    'critical_strike', 'jab', 'cold_arrow', 'multiple_shot', 'dodge',
    'power_strike', 'poison_javelin', 'exploding_arrow', 'slow_missiles',
    'avoid', 'impale', 'lightning_bolt', 'ice_arrow', 'guided_arrow',
    'penetrate', 'charged_strike', 'plague_javelin', 'strafe',
    'immolation_arrow', 'dopplezon', 'evade', 'fend', 'freezing_arrow',
    'valkyrie', 'pierce', 'lightning_strike', 'lightning_fury',
    'fire_bolt', 'warmth', 'charged_bolt', 'ice_bolt', 'frozen_armor',
    'inferno', 'static_field', 'telekinesis', 'frost_nova', 'ice_blast',
    'blaze', 'fire_ball', 'nova', 'lightning', 'shiver_armor',
    'fire_wall', 'enchant', 'chain_lightning', 'teleport', 'glacial_spike',
    'meteor', 'thunder_storm', 'energy_shield', 'blizzard',
    'chilling_armor', 'fire_mastery', 'hydra', 'lightning_mastery',
    'frozen_orb', 'cold_mastery', 'amplify_damage', 'teeth', 'bone_armor',
    'skeleton_mastery', 'raise_skeleton', 'dim_vision', 'weaken',
    'poison_dagger', 'corpse_explosion', 'clay_golem', 'iron_maiden',
    'terror', 'bone_wall', 'golem_mastery', 'raise_skeletal_mage',
    'confuse', 'life_tap', 'poison_explosion', 'bone_spear', 'blood_golem',
    'attract', 'decrepify', 'bone_prison', 'summon_resist', 'iron_golem',
    'lower_resist', 'poison_nova', 'bone_spirit', 'fire_golem', 'revive',
    'sacrifice', 'smite', 'might', 'prayer', 'resist_fire', 'holy_bolt',
    'holy_fire', 'thorns', 'defiance', 'resist_cold', 'zeal', 'charge',
    'blessed_aim', 'cleansing', 'resist_lightning', 'vengeance',
    'blessed_hammer', 'concentration', 'holy_freeze', 'vigor',
    'conversion', 'holy_shield', 'holy_shock', 'sanctuary', 'meditation',
    'fist_of_the_heavens', 'fanaticism', 'conviction', 'redemption',
    'salvation', 'bash', 'sword_mastery', 'axe_mastery', 'mace_mastery',
    'howl', 'find_potion', 'leap', 'double_swing', 'pole_arm_mastery',
    'throwing_mastery', 'spear_mastery', 'taunt', 'shout', 'stun',
    'double_throw', 'increased_stamina', 'find_item', 'leap_attack',
    'concentrate', 'iron_skin', 'battle_cry', 'frenzy', 'increased_speed',
    'battle_orders', 'grim_ward', 'whirlwind', 'berserk',
    'natural_resistance', 'war_cry', 'battle_command', 'fire_hit',
    'un_holy_bolt', 'skeleton_raise', 'maggot_egg', 'shaman_fire', 'magott_up',
    'magott_down', 'magott_lay', 'andrial_spray', 'jump', 'swarm_move',
    'nest', 'quick_strike', 'vampire_fireball', 'vampire_firewall',
    'vampire_meteor', 'gargoyle_trap', 'spider_lay', 'vampire_heal',
    'vampire_raise', 'submerge', 'fetish_aura', 'fetish_inferno',
    'zakarum_heal', 'emerge', 'resurrect', 'bestow', 'missile_skill1',
    'mon_teleport', 'prime_lightning', 'prime_bolt', 'prime_blaze',
    'prime_firewall', 'prime_spike', 'prime_ice_nova', 'prime_poisonball',
    'prime_poison_nova', 'diab_light', 'diab_cold', 'diab_fire',
    'finger_mage_spider', 'diab_wall', 'diab_run', 'diab_prison',
    'poison_ball_trap', 'andy_poison_bolt', 'hireable_missile', 'desert_turret',
    'arcane_tower', 'mon_blizzard', 'mosquito', 'cursed_ball_trap_right',
    'cursed_ball_trap_left', 'mon_frozen_armor', 'mon_bone_armor', 'mon_bone_spirit',
    'mon_curse_cast', 'hell_meteor', 'regurgitator_eat', 'mon_frenzy',
    'queen_death', 'scroll_of_identify', 'book_of_identify',
    'scroll_of_townportal', 'book_of_townportal', 'raven', 'plague_poppy',
    'wearwolf', 'shape_shifting', 'firestorm', 'oak_sage',
    'summon_spirit_wolf', 'wearbear', 'molten_boulder', 'arctic_blast',
    'cycle_of_life', 'feral_rage', 'maul', 'eruption', 'cyclone_armor',
    'heart_of_wolverine', 'summon_fenris', 'rabies', 'fire_claws',
    'twister', 'vines', 'hunger', 'shock_wave', 'volcano', 'tornado',
    'spirit_of_barbs', 'summon_grizzly', 'fury', 'armageddon', 'hurricane',
    'fire_trauma', 'claw_mastery', 'psychic_hammer', 'tiger_strike',
    'dragon_talon', 'shock_field', 'blade_sentinel', 'quickness',
    'fists_of_fire', 'dragon_claw', 'charged_bolt_sentry',
    'wake_of_fire_sentry', 'weapon_block', 'cloak_of_shadows',
    'cobra_strike', 'blade_fury', 'fade', 'shadow_warrior',
    'claws_of_thunder', 'dragon_tail', 'lightning_sentry', 'inferno_sentry',
    'mind_blast', 'blades_of_ice', 'dragon_flight', 'death_sentry',
    'blade_shield', 'venom', 'shadow_master', 'royal_strike',
    'wake_of_destruction_sentry', 'imp_inferno', 'imp_fireball',
    'baal_taunt', 'baal_corpse_explode', 'baal_monster_spawn',
    'catapult_charged_ball', 'catapult_spike_ball', 'suck_blood',
    'cry_help', 'healing_vortex', 'teleport_2', 'self-resurrect',
    'vine_attack', 'overseer_whip', 'barbs_aura', 'wolverine_aura',
    'oak_sage_aura', 'imp_fire_missile', 'impregnate', 'siege_beast_stomp',
    'minion_spawner', 'catapult_blizzard', 'catapult_plague', 'catapult_meteor',
    'bolt_sentry', 'corpse_cycler', 'death_maul', 'defense_curse',
    'blood_mana', 'mon_inferno_sentry', 'mon_death_sentry',
    'sentry_lightning', 'fenris_rage', 'baal_tentacle', 'baal_nova',
    'baal_inferno', 'baal_cold_missiles', 'megademon_inferno',
    'evil_hut_spawner', 'countess_firewall', 'imp_bolt', 'horror_arctic_blast',
    'death_sentry_ltng', 'vine_cycler', 'bear_smite', 'resurrect2',
    'blood_lord_frenzy', 'baal_teleport', 'imp_teleport',
    'baal_clone_teleport', 'zakarum_lightning', 'vampire_missile',
    'mephisto_missile', 'doom_knight_missile', 'rogue_missile', 'hydra_missile',
    'necromage_missile', 'mon_bow', 'mon_fire_arrow', 'mon_cold_arrow',
    'mon_exploding_arrow', 'mon_freezing_arrow', 'mon_power_strike',
    'succubus_bolt', 'meph_frost_nova', 'mon_ice_spear', 'shaman_ice',
    'diablogeddon', 'delerium_change', 'nihlathak_corpse_explosion',
    'serpent_charge', 'trap_nova', 'un_holy_bolt_ex', 'shaman_fire_ex',
    'imp_fire_missile_ex')

class SkillsAdapter(Adapter):
    def _encode(self, obj, context):
        return skills_list.index(obj)

    def _decode(self, obj, context):
        return skills_list[obj]

def Skill(name):
    return SkillsAdapter(ULInt16(name))
